### ISSUE TITLE
UploadLocationService never fired

### ISSUE THREAD

**Issue by wluijk** [martinraj/tracking-location-provider-android#1]
I dont get the UploadLocationService fired from the JobScheduler. Can you guide me through some checkpoints?

**Edit**: I found the commented call to UpdateLocationService.

**Comment by martinraj** [comment]
Hi,
I have commented the triggering code.

if(cd.isConnectingToInternet()) { // check whether internet is available or not
                            updatesList.add(location); //if available add latest location point and send list to server
                            Intent i1 = new Intent(LocationJobService.this, UploadLocationService.class);
                            i1.putParcelableArrayListExtra("points", updatesList);
**//                            startService(i1); //i have disabled the call as the server URL in intent service is dummy URL. Change the URL to your server URL and call this intent service. Uncomment this ;ine to trigger upload location service and dont forget to add it in manifest file**
                            updatesList.clear();
                        }else{ // if there is no internet connection
                            updatesList.add(location); // add location points to the list
                        }
