### ISSUE TITLE
Start on boot

### ISSUE THREAD

**Issue by wluijk** [martinraj/tracking-location-provider-android#2]
Do i overlook it or does the backroundservice not start at boot when it was on while the device was stopped?

**Comment by wluijk** [comment]
The app is marked as using too much battery by the system. I think this is also the reason that the background service stops running on a moment. What is the strategy to stay under the radar for the battery? Do we need an kind of watchdog mechanism?

**Comment by martinraj** [comment]
Hi, I have updated the code. Now service will start automatically after booting.

**Comment by opnsrcntrbtr** [comment]
Great work Martin! I found your source really useful for my app specific use case. However, I didn't find any code to start service automatically after boot is completed. 
The code additions below work for me. Can you point out the exact code, if you are handling it differently.

In Manifest.xml add: 

`<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />`

```
<application
...
<receiver
            android:name=".TrackerBroadcastReceiver"
            android:enabled="true"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

```

Add a TrackerBroadcastReceiver class as below:

```
package com.marty.track;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;

public class TrackerBroadcastReceiver extends BroadcastReceiver {

    @Override
    public void onReceive(Context context, Intent intent) {
        // This method is called when the BroadcastReceiver is receiving
        // an Intent broadcast, which in this case is a power boot completed.
        if (intent.getAction().equals(Intent.ACTION_BOOT_COMPLETED)) {
            Intent start = new Intent(context, MainActivity.class);
            start.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            context.startActivity(start);
        }
    }
}
```
