### ISSUE TITLE
App marked bad due to battery consumption

### ISSUE THREAD

**Issue by wluijk** [martinraj/tracking-location-provider-android#3]
The app is marked as using too much battery by the system. I think this is also the reason that the background service stops running on a moment. What is the strategy to stay under the radar for the battery? Do we need an kind of watchdog mechanism?

**Comment by martinraj** [comment]
This is an example of live tracking cabs or trucks where drivers will be plugged in always. So it consumes much battery for accuracy. 
You can reduce it by changing below parameters.
mLocationRequest = new LocationRequest();

mLocationRequest.setInterval(10000); ///will check for location update every 10 sec

mLocationRequest.setFastestInterval(5000); //will check for location update every 5 sec

mLocationRequest.setSmallestDisplacement(10); //just 10 meters

mLocationRequest.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY);
//High_Accuracy will use both GPS and wifi or mobile network inputs.

**Comment by martinraj** [comment]
Will upload another repository today about getting locations based on time interval using alarm manager. That will consume less battery.

**Comment by martinraj** [comment]
Hi, I have created a new repository for getting locations by triggering the alarm on periodic intervals. Do check it.[click to view](https://github.com/martinraj/Android-Geo-Remainder-Alarm)
